services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: desikau-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - desikau-network
    depends_on:
      - db
      - mailhog

  nginx:
    image: nginx:alpine
    container_name: desikau-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desikau-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: desikau-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-desikau}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-desikau}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - desikau-network

  node:
    image: node:18-alpine
    container_name: desikau-node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - desikau-network
    tty: true

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: desikau-stripe
    env_file:
      - ./src/.env
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET:-}
    networks:
      - desikau-network
    depends_on:
      - nginx
    command: listen --forward-to http://nginx/stripe/webhook --api-key ${STRIPE_SECRET:-}
    tty: true
    stdin_open: true
    profiles:
      - stripe

  mailhog:
      image: mailhog/mailhog:latest
      container_name: desikau-mailhog
      ports:
        - "8025:8025"
        - "1025:1025"
      networks:
        - desikau-network

networks:
  desikau-network:
    name: desikau-network
    driver: bridge

volumes:
  db-data:
